[package]
name = "peakcan-basic"
version = "0.1.0"
edition = "2021"

resolver = "2"
[workspace]
members = [
    "peakcan-basic-sys",
]

[dependencies]
peakcan-basic-sys = { path = "./peakcan-basic-sys" }
